name: ecurie
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.9.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  date_field: ^3.0.5
  flutter_localization: ^0.1.13
  fluro: ^2.0.5
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  table_calendar: ^3.0.9
  multi_select_flutter: ^4.1.3
  flutter_image_compress: ^2.0.4
  fs: ^2.0.0
  provider: ^6.0.5
  flutter_session_manager: ^1.0.3
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/myGentleMan.jpg