name: ecurie
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.9.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  date_field: ^3.0.5
  flutter_localization: ^0.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
